### ISSUE TITLE
nofollow and _blank

### ISSUE THREAD

**Issue by fpellet** [Erudika/scoold#298]
Hello,

In order to avoid spam, it would be interesting to add `rel="nofollow"` on links included in questions, answers and comments.

Another interesting option would be to force the opening of a link in another tab with `target="_blank"` and `rel="noopener noreferrer"`.

Does this seem interesting to you?
We need to modify para as well.

**Comment by albogdano** [comment]
Good idea! I am more hesitant to add `target="_blank"` because of [these reasons](https://css-tricks.com/use-target_blank/). But if we can have each link in each Scoold post have the attributes `rel="nofollow noreferrer"`, that would be great.

I think this can be implemented inside [`Utils.java`](https://github.com/Erudika/para/blob/master/para-core/src/main/java/com/erudika/para/core/utils/Utils.java#L468) in Para core using [this example](https://github.com/vsch/flexmark-java/blob/master/flexmark-java-samples/src/com/vladsch/flexmark/java/samples/AttributeProviderSample.java). The goal is to create a custom Flexmark extension for adding the `rel` attribute to every link when Markdown is parsed.
