### ISSUE TITLE
Question doesn't show on custom space.

### ISSUE THREAD

**Issue by showaid** [Erudika/scoold#31]
Hi @albogdano,

I found out an issue about question.
The question which is asked on a custom space(e.g. SpaceA) doesn't show on the space.

![screenshot - 2018-02-14 10_47_37](https://user-images.githubusercontent.com/1582582/36184086-0d7f5346-1175-11e8-90bc-c9333b4b38d0.png)
=> The question is for SpaceA

![screenshot - 2018-02-14 10_48_14](https://user-images.githubusercontent.com/1582582/36184091-12bc4684-1175-11e8-9544-28064c21afe0.png)
=> The name of space seems wrong after the save.

![screenshot - 2018-02-14 10_48_37](https://user-images.githubusercontent.com/1582582/36184181-894947ca-1175-11e8-80c2-46a7b40d5a24.png)
=> The question doesn't appear in SpaceA

![screenshot - 2018-02-14 10_48_59](https://user-images.githubusercontent.com/1582582/36184204-b39ffd5c-1175-11e8-98d1-46c7636f46c2.png)
=> It's showing on the default space instead.

Please look into this.
Thank you!

**Comment by albogdano** [comment]
You might have to "edit" your existing questions and save them to update their `space` field. Previously questions were saved with the shorthand space id, e.g. "scooldspace:test" instead of the full id "scooldspace:test:Test space". This was the root cause of these issues. I hope everything works well now.
