### ISSUE TITLE
posts_need_approval -- **new posts require approval**

### ISSUE THREAD

**Issue by cimenta** [Erudika/scoold#422]
hi

I have set posts_need_approval =  true in server settings and was expecting that new questions must be approved in order to be visible to others. But it is not the case.... It looks like the settings of a space **new posts require approval** must be checked.

Question1:
What is the relationship between the server setting and space setting?

I have unapproved questions - see the screenshot
![image](https://github.com/Erudika/scoold/assets/1837850/9eda98e4-d2a7-4566-9c45-340848c9d7ae)

Question2:
But when using the filter unapproved no unapproved question is shown. Is that bacause scoold is using unapproved in two different meanings?

Question3:
could you add a filter for questions that needs to be approved to be visible? Could you make it more clear (background color) that it must be approved?

thank you
Radek

**Comment by albogdano** [comment]
Q1: The space setting overwrites the server settings, so if you have `scoold.posts_need_approval = true` that would work for the default space but every other private space will not require approval unless you explicitly check the checkbox.
Does that feel confusing? We could change it so that the server setting is global and sets all checkboxes in all spaces to true, meaning all spaces require approval by default.

Q2: Yes, the filter is not for questions waiting for approval but for questions without an approved answer (with a green checkmark)

Q3: I could but it would clutter the space on the top of the main page as it already has lots of filters there.
You can see all questions waiting for approval on the Reports page and you should get a notification.
If you don't see it set `posts_need_approval = true` (this situation will be fixed soon so that you will always see all unapproved questions there).
